[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]
panic-abort-tests = true

[build]
target = "x86_64-test_os.json"
rustflags = ["-C", "link-arg=-Map=kernel.map"]